# -*- coding: utf-8 -*-
"""Best Time To Buy and Sell Stock.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D2FSHUuZTQpDeevn-rc6fzPtcFfnk35U
"""

##function definition
## Time Complexity: O(n)
## Space Complexity: O(1)
def findMaxProfit(prices):
  min_price=float('inf')
  max_profit=0
  for i in range(len(prices)):
    if prices[i]<min_price:
      min_price=prices[i]
    elif prices[i]-min_price>max_profit:
      max_profit=prices[i]-min_price
  return max_profit


## Driver code
prices=[7,5,3,6,2,15]
maxProfit=findMaxProfit(prices)
print(f"The maximum profit of buy and sell the stock is {maxProfit}")

