# -*- coding: utf-8 -*-
"""Collinear Points.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qgP0oAIvthmmqGqbw6wHcB3jzTaswx0B
"""

## Approach 1:Using slope concept
## Time Complexity:O(1)
## Space Complexity: O(1)
##Method definition
def iscollinearPoints(x1,x2,x3,y1,y2,y3):
  if((y2-y1)*(x3-x2)==(y3-y2)*(x2-x1)):
    print("Given points are collinear")
  else:
    print("Given points are non collinear")



## Driver code
x1,x2,x3,y1,y2,y3=1,1,1,6,0,9
iscollinearPoints(x1,x2,x3,y1,y2,y3)

##Approach 2:Using area of traingle
##Time Complexity: O(1)
## Space Complexity:O(1)
def iscollinearPoints(x1,x2,x3,y1,y2,y3):
  area=0.5*(x1*(y2-y3)+x2*(y3-y1)+x3*(y1-y2))
  if area==0:
    print("Given points are collinear")
  else:
    print("Given points are non collinear")

## Driver code
x1,x2,x3,y1,y2,y3=1,1,1,6,0,9
iscollinearPoints(x1,x2,x3,y1,y2,y3)

