# -*- coding: utf-8 -*-
"""Insertion_Sort_Implementation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ihOfAn86kswjgJr2GW9E1zzlF-hs7hh
"""

##function definition
def insertionSort(arr):
  for i in range(1,len(arr)):
    key=arr[i]
    j=i-1
    while j>=0 and key<arr[j]:
      arr[j+1]=arr[j]
      j=j-1
    arr[j+1]=key
  return arr


## Driver code
arr=[9,5,1,4,3]
## function calling
result=insertionSort(arr)
print(f"Sorted array after applying the insertion sort is: {result}")

